# Site settings

title: "Scorecard"

description: "A digital scorecard that you can use at home as you watch the Eurovision Song Contest."

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://scorecard.johnpe.art"
author: "John Peart"

# Images and assets
image-path: "/assets/images"
css-path: "/assets/styles"
js-path: "/assets/scripts"

social-media-image: "/assets/images/site/social-media.png"

theme-colour: "#009fe3"

favicon: "/favicon.ico"
favicon-svg: "/assets/images/site/favicon.svg"
favicon-pinned-svg: "/assets/images/site/favicon-pinned-svg.svg"
favicon-large-png: "/assets/images/site/favicon-large-png.png"
launch-image: "/assets/images/site/launch.png"

# Social settings
twitter-url: "https://twitter.com/johnpeart" # Twitter handle i.e. joebloggs
twitter-handle: "johnpeart" # Twitter handle i.e. joebloggs

mastodon-url: "https://mastodon.social/@johnpeart"
mastodon-handle: "johnpeart@mastodon.social"

github-url:  "https://github.com/johnpeart"
github-handle:  "johnpeart"

analytics: false

# Site header

header: true

# Config

event: final # semifinal or final

# Collections

collections:
    pages:
        output: true
        permalink: /:path/
        defaults:
            values:
                layout: page
    scorecards:
        output: true
        permalink: /:path/
        defaults:
            values:
                layout: scorecard

# Plugins and build settings

markdown: kramdown
future: false
sass:
    sass_dir: _sass




